version: "3"
services:
  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole: 
    image: 'pihole/pihole:latest'
    container_name: pihole
    hostname: pihole
    restart: always  
    network_mode: bridge
    ports:
      - "53:53/tcp"
      - "53:53/udp"
        #     - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8053:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'b2K+3+tKst'
        # Volumes store your data between container upgrades
    volumes:
      - '/etc/pihole:/etc/pihole'
      - '/etc/dnsmasq.d:/etc/dnsmasq.d'    
        #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)      
