version: '3'

services:
  app:
    container_name: portainer
    image: 'cr.portainer.io/portainer/portainer-ce:latest'
    restart: always
    network_mode: bridge
      #networks:
      #- ngnix_proxy_manager_default
      #expose:
      #- '9443/tcp'
      #- '8000/tcp'
    ports:
      - '9443:9443'
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
        #networks:
        #ngnix_proxy_manager_default:
        #external: true
volumes:
    data:
