version: '3.3'
services:
    transmission-openvpn:
        image: haugene/transmission-openvpn
        cap_add:
            - NET_ADMIN
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=bahamas,ca_toronto,ca_montreal,mexico
            - OPENVPN_USERNAME=admin
            - OPENVPN_PASSWORD=password
            - LOCAL_NETWORK=192.168.0.0/24
              #            - LOG_TO_STDOUT=true # transmission logs to stdout
              #            - OPENVPN_OPTS=--inactive 3600 --ping 10 --pring-exit 60
              #            - PUID=1000
              #            - PGID=1000
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
            - '8888:8888'
        volumes:
          - '/srv/torrents:/data'
        dns:
          - '8.8.8.8'
          - '8.8.4.4'
